include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - docs/**
    - build/**
    - app/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    unawaited_futures: true
    prefer_final_locals: true
